- name: Demo on variables
  hosts: all
  vars:
    URL: playbook.com
    Founder: Rajesh
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg:
          - url = {{ URL }}
            " {{ Founder }} "