- name: Demo on variables
  hosts: all
  vars:
    URL: playbook.com
    Founder: Rajesh
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg:
          - url = {{ URL }}
          - "{{Founder}} Quotes are required when var is at first"

- name: Demo on file var
  hosts: all
  vars_files:
    - sample_var.yml
  tasks:
    - name: Printing var from file
      ansible.builtin.debug:
        msg: url = {{URL}}